services:
  - type: web
    name: cobijo-vzla
    env: docker
    plan: free
    healthCheckPath: /admin/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.1