# Generated by Django 6.1 on 2026-09-10 22:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_ine', models.CharField(blank=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RefugioExistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('capacidad_total', models.IntegerField()),
                ('capacidad_disponible', models.IntegerField()),
                ('servicios', models.JSONField(blank=True, default=list)),
                ('operativo', models.BooleanField(default=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('horario', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Refugio existente',
                'verbose_name_plural': 'Refugios existentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SitioCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('capacidad_maxima', models.IntegerField(default=100)),
                ('costo_apertura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_operacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo_terreno', models.CharField(blank=True, max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sitio candidato',
                'verbose_name_plural': 'Sitios candidatos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(help_text='Punto, polígono o multipolígono que delimita la zona', srid=4326)),
                ('nivel_alerta', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('heridos', models.IntegerField(default=0)),
                ('fallecidos', models.IntegerField(default=0)),
                ('damnificados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Zona afectada',
                'verbose_name_plural': 'Zonas afectadas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParametrosModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escenario', models.CharField(max_length=200)),
                ('tipo_modelo', models.CharField(choices=[('pmediana', 'P-Mediana'), ('pcentro', 'P-Centro'), ('cobertura', 'Cobertura Máxima'), ('capacidades', 'Localización con Capacidades')], max_length=30)),
                ('p', models.IntegerField(default=3, help_text='Número de centros a abrir')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('radio_cobertura', models.FloatField(default=5000, help_text='Radio de cobertura en metros')),
                ('ponderador_vulnerabilidad', models.FloatField(default=1.0)),
                ('ponderador_heridos', models.FloatField(default=1.0)),
                ('ponderador_fallecidos', models.FloatField(default=1.0)),
                ('ponderador_damnificados', models.FloatField(default=1.0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('filtro_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado')),
            ],
            options={
                'verbose_name': 'Parámetros de modelo',
                'verbose_name_plural': 'Parámetros de modelo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_ine', models.CharField(blank=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('poblacion', models.IntegerField(default=0)),
                ('densidad_poblacional', models.FloatField(default=0.0)),
                ('indice_vulnerabilidad', models.FloatField(default=0.5)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='core.estado')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'ordering': ['estado__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuntoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('poblacion', models.IntegerField(default=0)),
                ('vulnerabilidad', models.FloatField(default=0.5)),
                ('descripcion', models.TextField(blank=True)),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_demanda', to='core.parroquia')),
            ],
            options={
                'verbose_name': 'Punto de demanda',
                'verbose_name_plural': 'Puntos de demanda',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoOptimizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('datos_json', models.JSONField()),
                ('parametros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.parametrosmodelo')),
            ],
            options={
                'verbose_name': 'Resultado de optimización',
                'verbose_name_plural': 'Resultados de optimización',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
