# Generated by Django 6.1 on 2026-09-10 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('emergencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaafectada',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_afectadas', to='emergencias.evento'),
        ),
        migrations.AlterUniqueTogether(
            name='parroquia',
            unique_together={('nombre', 'estado')},
        ),
    ]
