# Generated by Django 6.1 on 2026-09-19 04:22

import django.contrib.gis.db.models.fields
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('emergencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodemanda',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitiocandidato',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='codigo_ine',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código INE'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometría'),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='p',
            field=models.IntegerField(default=3, help_text='Número de centros a abrir', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='ponderador_damnificados',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='ponderador_fallecidos',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='ponderador_heridos',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='ponderador_vulnerabilidad',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='radio_cobertura',
            field=models.FloatField(default=5000, help_text='Radio de cobertura en metros', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='codigo_ine',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código INE'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='densidad_poblacional',
            field=models.FloatField(default=0.0, help_text='Habitantes por km²', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometría'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='indice_vulnerabilidad',
            field=models.FloatField(default=0.5, help_text='Índice de 0 (baja) a 1 (alta)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='poblacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='puntodemanda',
            name='poblacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='puntodemanda',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='puntodemanda',
            name='vulnerabilidad',
            field=models.FloatField(default=0.5, help_text='Índice de 0 (baja) a 1 (alta)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='refugioexistente',
            name='capacidad_disponible',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidad disponible'),
        ),
        migrations.AlterField(
            model_name='refugioexistente',
            name='capacidad_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidad total'),
        ),
        migrations.AlterField(
            model_name='refugioexistente',
            name='servicios',
            field=models.JSONField(blank=True, default=list, help_text='Lista de servicios disponibles'),
        ),
        migrations.AlterField(
            model_name='refugioexistente',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='sitiocandidato',
            name='capacidad_maxima',
            field=models.IntegerField(default=100, help_text='Personas que puede albergar', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sitiocandidato',
            name='costo_apertura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de apertura'),
        ),
        migrations.AlterField(
            model_name='sitiocandidato',
            name='costo_operacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de operación'),
        ),
        migrations.AlterField(
            model_name='sitiocandidato',
            name='disponible',
            field=models.BooleanField(default=True, help_text='¿Está disponible para ser seleccionado?'),
        ),
        migrations.AlterField(
            model_name='sitiocandidato',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='zonaafectada',
            name='damnificados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zonaafectada',
            name='fallecidos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zonaafectada',
            name='heridos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='parroquia',
            index=models.Index(fields=['estado', 'nombre'], name='core_parroq_estado__65308a_idx'),
        ),
        migrations.AddIndex(
            model_name='puntodemanda',
            index=models.Index(fields=['parroquia'], name='core_puntod_parroqu_a6bc51_idx'),
        ),
        migrations.AddIndex(
            model_name='refugioexistente',
            index=models.Index(fields=['operativo'], name='core_refugi_operati_92dc51_idx'),
        ),
        migrations.AddIndex(
            model_name='sitiocandidato',
            index=models.Index(fields=['disponible'], name='core_sitioc_disponi_53632e_idx'),
        ),
        migrations.AddIndex(
            model_name='zonaafectada',
            index=models.Index(fields=['nivel_alerta'], name='core_zonaaf_nivel_a_c3271a_idx'),
        ),
        migrations.AddIndex(
            model_name='zonaafectada',
            index=models.Index(fields=['fecha_inicio'], name='core_zonaaf_fecha_i_67eb73_idx'),
        ),
    ]
