# Generated by Django 6.1 on 2026-09-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_puntodemanda_creado_sitiocandidato_creado_and_more'),
        ('emergencias', '0002_alter_evento_options_alter_reporte_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parametrosmodelo',
            constraint=models.CheckConstraint(condition=models.Q(('p__gte', 1)), name='parametros_p_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='parametrosmodelo',
            constraint=models.CheckConstraint(condition=models.Q(('presupuesto__isnull', True), ('presupuesto__gte', 0), _connector='OR'), name='parametros_presupuesto_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='parametrosmodelo',
            constraint=models.CheckConstraint(condition=models.Q(('radio_cobertura__gte', 0)), name='parametros_radio_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='refugioexistente',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_total__gte', 0)), name='refugio_capacidad_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='refugioexistente',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_disponible__gte', 0), ('capacidad_disponible__lte', models.F('capacidad_total'))), name='refugio_capacidad_disponible_valida'),
        ),
        migrations.AddConstraint(
            model_name='zonaafectada',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='zona_fecha_fin_valida'),
        ),
        migrations.AddConstraint(
            model_name='zonaafectada',
            constraint=models.CheckConstraint(condition=models.Q(('heridos__gte', 0)), name='zona_heridos_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='zonaafectada',
            constraint=models.CheckConstraint(condition=models.Q(('fallecidos__gte', 0)), name='zona_fallecidos_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='zonaafectada',
            constraint=models.CheckConstraint(condition=models.Q(('damnificados__gte', 0)), name='zona_damnificados_gte_0'),
        ),
    ]
