# Generated by Django 6.1
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_puntodemanda_creado_sitiocandidato_creado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accion', models.CharField(db_index=True, max_length=80)),
                ('metodo', models.CharField(max_length=10)),
                ('ruta', models.CharField(max_length=500)),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('error', 'Error'), ('rechazado', 'Rechazado')], db_index=True, default='exitoso', max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Bitácora del sistema',
                'ordering': ['-fecha'],
                'indexes': [
                    models.Index(fields=['usuario', '-fecha'], name='core_regis_usuario_8d5c8a_idx'),
                    models.Index(fields=['accion', '-fecha'], name='core_regis_accion_6bcbf2_idx'),
                    models.Index(fields=['resultado', '-fecha'], name='core_regis_resultado_8f7e0d_idx'),
                ],
            },
        ),
    ]
