# Generated by Django 6.1 on 2026-09-30 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parametrosmodelo_parametros_p_gte_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('IMPORT', 'Importación'), ('EXPORT', 'Exportación'), ('OPTIMIZATION', 'Optimización'), ('COMMAND', 'Comando'), ('REPORT', 'Reporte')], db_index=True, max_length=30)),
                ('modelo', models.CharField(blank=True, db_index=True, max_length=150)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('objeto_repr', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('ruta', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], db_index=True, default='exitoso', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', '-fecha_hora'], name='core_auditl_usuario_c27bae_idx'), models.Index(fields=['accion', '-fecha_hora'], name='core_auditl_accion_ad632a_idx'), models.Index(fields=['modelo', 'objeto_id'], name='core_auditl_modelo_2c1abf_idx')],
            },
        ),
    ]
