# Generated by Django 6.1
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_registroauditoria'),
    ]
    operations = [
        migrations.CreateModel(
            name='RegistroVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_version', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modelo', models.CharField(db_index=True, max_length=150)),
                ('objeto_id', models.CharField(db_index=True, max_length=100)),
                ('operacion', models.CharField(choices=[('creado', 'Creado'), ('actualizado', 'Actualizado'), ('eliminado', 'Eliminado')], max_length=20)),
                ('datos', models.JSONField()),
                ('ruta', models.CharField(blank=True, max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión histórica',
                'verbose_name_plural': 'Versiones históricas',
                'ordering': ['-fecha_version'],
                'indexes': [
                    models.Index(fields=['modelo', 'objeto_id', '-fecha_version'], name='core_regist_modelo_1a3b3d_idx'),
                    models.Index(fields=['modelo', '-fecha_version'], name='core_regist_modelo_0c5a6a_idx'),
                ],
            },
        ),
    ]
