# Generated by Django 6.1
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Sincroniza con los validadores de costos definidos en el modelo.

    La aplicación ya estaba operativa; esta migración solo alinea el estado
    histórico de Django con los MinValueValidator(0) presentes en el modelo.
    """

    dependencies = [
        ("core", "0012_integridad_operativa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitiocandidato",
            name="costo_apertura",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Costo de apertura",
            ),
        ),
        migrations.AlterField(
            model_name="sitiocandidato",
            name="costo_operacion",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Costo de operación",
            ),
        ),
    ]
