# Generated by Django 6.1
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_alter_sitiocandidato_costos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitiocandidato',
            name='parroquia',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name='sitios_candidatos',
                to='core.parroquia',
            ),
        ),
        migrations.AddField(
            model_name='refugioexistente',
            name='parroquia',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name='refugios_existentes',
                to='core.parroquia',
            ),
        ),
        migrations.AddIndex(
            model_name='sitiocandidato',
            index=models.Index(fields=['parroquia'], name='core_sitio_parroqui_idx'),
        ),
        migrations.AddIndex(
            model_name='refugioexistente',
            index=models.Index(fields=['parroquia'], name='core_refugio_parroqui_idx'),
        ),
    ]
