# Generated by Django 6.1 on 2026-10-10 03:27

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ubicacion_parroquia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrosmodelo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Simulación', 'verbose_name_plural': 'Simulaciones'},
        ),
        migrations.RemoveConstraint(
            model_name='zonaafectada',
            name='zona_heridos_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='zonaafectada',
            name='zona_fallecidos_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='zonaafectada',
            name='zona_damnificados_gte_0',
        ),
        migrations.RemoveIndex(
            model_name='zonaafectada',
            name='core_zonaaf_nivel_a_c3271a_idx',
        ),
        migrations.RemoveIndex(
            model_name='zonaafectada',
            name='core_zonaaf_fecha_i_67eb73_idx',
        ),
        migrations.RenameIndex(
            model_name='refugioexistente',
            new_name='core_refugi_parroqu_7e73ef_idx',
            old_name='core_refugio_parroqui_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='core_regis_resultado_idx',
            old_name='core_regis_resultado_8f7e0d_idx',
        ),
        migrations.RenameIndex(
            model_name='sitiocandidato',
            new_name='core_sitioc_parroqu_4ce192_idx',
            old_name='core_sitio_parroqui_idx',
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='p',
            field=models.IntegerField(default=3, help_text='Número de centros a abrir'),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='ponderador_damnificados',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='ponderador_fallecidos',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='ponderador_heridos',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='ponderador_vulnerabilidad',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='parametrosmodelo',
            name='radio_cobertura',
            field=models.FloatField(default=5000, help_text='Radio de cobertura en metros'),
        ),
        migrations.AlterField(
            model_name='registroversion',
            name='fecha_version',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='zonaafectada',
            name='damnificados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonaafectada',
            name='fallecidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonaafectada',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zonaafectada',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='zonaafectada',
            name='heridos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonaafectada',
            name='nivel_alerta',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=20),
        ),
    ]
