# Generated by Django 6.1 on 2026-10-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_parametrosmodelo_options'),
        ('emergencias', '0002_alter_evento_options_alter_reporte_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zonaafectada',
            index=models.Index(fields=['nivel_alerta'], name='core_zonaaf_nivel_a_c3271a_idx'),
        ),
        migrations.AddIndex(
            model_name='zonaafectada',
            index=models.Index(fields=['fecha_inicio'], name='core_zonaaf_fecha_i_67eb73_idx'),
        ),
        migrations.AddConstraint(
            model_name='zonaafectada',
            constraint=models.CheckConstraint(condition=models.Q(('heridos__gte', 0)), name='zona_heridos_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='zonaafectada',
            constraint=models.CheckConstraint(condition=models.Q(('fallecidos__gte', 0)), name='zona_fallecidos_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='zonaafectada',
            constraint=models.CheckConstraint(condition=models.Q(('damnificados__gte', 0)), name='zona_damnificados_gte_0'),
        ),
    ]
