# Generated by Django 6.1 on 2026-10-10 06:06

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_limpiar_parroquias_duplicadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_ine', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código INE')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometría')),
                ('poblacion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('densidad_poblacional', models.FloatField(default=0.0, help_text='Habitantes por km²', validators=[django.core.validators.MinValueValidator(0)])),
                ('indice_vulnerabilidad', models.FloatField(default=0.5, help_text='Índice de 0 (baja) a 1 (alta)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='core.estado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['estado__nombre', 'nombre'],
                'indexes': [models.Index(fields=['estado', 'nombre'], name='core_munici_estado__dd99c9_idx')],
                'unique_together': {('nombre', 'estado')},
            },
        ),
    ]
