# Generated by Django 6.1 on 2026-10-10 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_create_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parroquias', to='core.municipio'),
        ),
    ]
