# Generated by Django 6.1 on 2026-10-10 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_parroquia_municipio_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaafectada',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_afectadas', to='core.parroquia'),
        ),
    ]
