# Generated by Django 6.1 on 2026-10-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_asignar_parroquia_zonas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parroquia',
            unique_together={('nombre', 'municipio')},
        ),
        migrations.AddIndex(
            model_name='parroquia',
            index=models.Index(fields=['municipio', 'nombre'], name='core_parroq_municip_7a6601_idx'),
        ),
    ]
