# Generated by Django 6.1 on 2026-09-10 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('inundacion', 'Inundación'), ('terremoto', 'Terremoto'), ('deslizamiento', 'Deslizamiento'), ('incendio', 'Incendio'), ('otro', 'Otro')], max_length=30)),
                ('fecha', models.DateTimeField()),
                ('magnitud', models.FloatField(blank=True, help_text='Magnitud o intensidad del evento', null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('verificado', models.BooleanField(default=False)),
                ('punto_demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.puntodemanda')),
                ('zona_afectada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.zonaafectada')),
            ],
        ),
    ]
