# Generated by Django 6.1 on 2026-09-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_puntodemanda_creado_sitiocandidato_creado_and_more'),
        ('emergencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha'], 'verbose_name': 'Reporte ciudadano', 'verbose_name_plural': 'Reportes ciudadanos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='activo',
            field=models.BooleanField(default=True, help_text='¿El evento sigue en curso?'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='magnitud',
            field=models.FloatField(blank=True, help_text='Magnitud o intensidad del evento (escala según tipo)', null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='autor',
            field=models.CharField(blank=True, help_text='Nombre o seudónimo del reportante (opcional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='verificado',
            field=models.BooleanField(default=False, help_text='¿Ha sido validado por un operador?'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['-fecha'], name='emergencias_fecha_5397bf_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['activo'], name='emergencias_activo_89ed4d_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo', 'activo'], name='emergencias_tipo_ae08b5_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['-fecha'], name='emergencias_fecha_5d1602_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['verificado'], name='emergencias_verific_5de43d_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['zona_afectada'], name='emergencias_zona_af_538dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['punto_demanda'], name='emergencias_punto_d_3f91de_idx'),
        ),
    ]
