# Generated by Django 6.1
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF')], max_length=10)),
                ('contenido', models.CharField(choices=[('zonas', 'Zonas afectadas'), ('general', 'Estadísticas generales')], max_length=20)),
                ('fecha_desde', models.DateTimeField(blank=True, null=True)),
                ('fecha_hasta', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=255)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('sin_datos', 'Sin datos'), ('error', 'Error'), ('rechazado', 'Rechazado')], db_index=True, max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de reporte',
                'verbose_name_plural': 'Bitácora de reportes',
                'ordering': ['-fecha_generacion'],
                'indexes': [
                    models.Index(fields=['usuario', '-fecha_generacion'], name='reportes_re_usuario__5b5e35_idx'),
                    models.Index(fields=['tipo', 'contenido', '-fecha_generacion'], name='reportes_re_tipo_7e6e2d_idx'),
                ],
            },
        ),
    ]
