# Generated by Django 6.1 on 2026-10-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_registroreporte_referencia'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registroreporte',
            new_name='reportes_re_usuario_78aa9e_idx',
            old_name='reportes_re_usuario__5b5e35_idx',
        ),
        migrations.RenameIndex(
            model_name='registroreporte',
            new_name='reportes_re_tipo_05d867_idx',
            old_name='reportes_re_tipo_7e6e2d_idx',
        ),
    ]
